name: Update models.json

on:
  release:
    types: [created]
  workflow_dispatch:

permissions: write-all

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generating models.json
        run: |
          python ./py/generateModelsJson.py
      - name: Commit files
        run: |
          git config --local user.email "2964459358@qq.com"
          git config --local user.name "Fallingfl"
          git add .
          git commit -m "[Update] $(cat ./data/version.txt)"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
